package br.com.infoTech.views;

import br.com.infoTech.controller.TelaClienteController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Wilson F.F.Souza
 */
public class TelaCliente extends javax.swing.JInternalFrame {

    private final TelaClienteController controller;

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
        controller = new TelaClienteController(this);
        controller.controlaBotoes("Iniciar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblIDCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        txtEndCliente = new javax.swing.JTextField();
        txtNumEndCliente = new javax.swing.JTextField();
        txtBairroCliente = new javax.swing.JTextField();
        txtCidCliente = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        txtFoneCel = new javax.swing.JFormattedTextField();
        txtFoneFixo = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnCadClie = new javax.swing.JButton();
        btnExClie = new javax.swing.JButton();
        btnEdClie = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtPesqCliente = new javax.swing.JTextField();
        btnConsClie = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Tela Cadastro de Clientes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ID Cliente:");

        lblIDCliente.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblIDCliente.setText("ID Cliente");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("* Nome:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Endereço:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Nº:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Bairro:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Cidade:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Estado:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Telefone Fixo:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("* Celular:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("* Email:");

        txtNomeCliente.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtEndCliente.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtEndCliente.setEnabled(false);

        txtNumEndCliente.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNumEndCliente.setEnabled(false);

        txtBairroCliente.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtBairroCliente.setEnabled(false);

        txtCidCliente.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCidCliente.setEnabled(false);

        cbEstado.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));
        cbEstado.setEnabled(false);

        try {
            txtFoneCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFoneCel.setEnabled(false);
        txtFoneCel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        try {
            txtFoneFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFoneFixo.setEnabled(false);
        txtFoneFixo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtEmail.setToolTipText("Email");
        txtEmail.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("* Campos Obrigatórios!");

        btnCadClie.setBackground(new java.awt.Color(255, 255, 255));
        btnCadClie.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCadClie.setForeground(new java.awt.Color(255, 255, 255));
        btnCadClie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infoTech/icons/AddUser.png"))); // NOI18N
        btnCadClie.setToolTipText("Cadastrar");
        btnCadClie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadClie.setPreferredSize(new java.awt.Dimension(85, 85));
        btnCadClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadClieActionPerformed(evt);
            }
        });

        btnExClie.setBackground(new java.awt.Color(255, 255, 255));
        btnExClie.setForeground(new java.awt.Color(255, 255, 255));
        btnExClie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infoTech/icons/DeleteUser.png"))); // NOI18N
        btnExClie.setToolTipText("Deletar");
        btnExClie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExClie.setEnabled(false);
        btnExClie.setPreferredSize(new java.awt.Dimension(85, 85));
        btnExClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExClieActionPerformed(evt);
            }
        });

        btnEdClie.setBackground(new java.awt.Color(255, 255, 255));
        btnEdClie.setForeground(new java.awt.Color(255, 255, 255));
        btnEdClie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infoTech/icons/UpdateUser.png"))); // NOI18N
        btnEdClie.setToolTipText("Editar");
        btnEdClie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdClie.setEnabled(false);
        btnEdClie.setPreferredSize(new java.awt.Dimension(85, 85));
        btnEdClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdClieActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infoTech/icons/Add.png"))); // NOI18N
        btnAdd.setToolTipText("Adicionar");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infoTech/icons/cancelar.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtPesqCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPesqCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqClienteKeyReleased(evt);
            }
        });

        btnConsClie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infoTech/icons/Lupa.png"))); // NOI18N
        btnConsClie.setToolTipText("Pesquisar");
        btnConsClie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Celular", "Email"
            }
        ));
        tblClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(txtPesqCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsClie, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeCliente)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEndCliente)
                                        .addGap(49, 49, 49))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBairroCliente)
                                            .addComponent(txtFoneFixo)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblIDCliente)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtFoneCel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNumEndCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtEmail)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(btnCadClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnExClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEdClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesqCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsClie))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblIDCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(txtEndCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumEndCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtFoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCadClie, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            controller.SalvarCliente();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        try {
            controller.AtualizaCampos();
            btnEdClie.setEnabled(true);
            btnExClie.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblClientesMouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        try {
            this.controller.AtualizaTabelaCliente();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnEdClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdClieActionPerformed
        controller.controlaBotoes("Editar");
    }//GEN-LAST:event_btnEdClieActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        controller.controlaBotoes("Iniciar");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadClieActionPerformed
        controller.controlaBotoes("Cadastrar");
    }//GEN-LAST:event_btnCadClieActionPerformed

    private void btnExClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExClieActionPerformed
        try {
            controller.excluiCliente();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExClieActionPerformed

    private void txtPesqClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqClienteKeyReleased
        if (txtPesqCliente.getText().isEmpty()) {
            try {
                controller.AtualizaTabelaCliente();
            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                controller.pesquisaDinamica();
                controller.AtualizaTabelaClienteNome();
            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtPesqClienteKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCadClie;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsClie;
    private javax.swing.JButton btnEdClie;
    private javax.swing.JButton btnExClie;
    public static javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIDCliente;
    private javax.swing.JTable tblClientes;
    public static javax.swing.JTextField txtBairroCliente;
    public static javax.swing.JTextField txtCidCliente;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtEndCliente;
    public static javax.swing.JFormattedTextField txtFoneCel;
    public static javax.swing.JFormattedTextField txtFoneFixo;
    public static javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNumEndCliente;
    private javax.swing.JTextField txtPesqCliente;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAdd() {
        return btnAdd;
    }

    public void setBtnAdd(JButton btnAdd) {
        this.btnAdd = btnAdd;
    }

    public JButton getBtnCadClie() {
        return btnCadClie;
    }

    public void setBtnCadClie(JButton btnCadClie) {
        this.btnCadClie = btnCadClie;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnConsClie() {
        return btnConsClie;
    }

    public void setBtnConsClie(JButton btnConsClie) {
        this.btnConsClie = btnConsClie;
    }

    public JButton getBtnEdClie() {
        return btnEdClie;
    }

    public void setBtnEdClie(JButton btnEdClie) {
        this.btnEdClie = btnEdClie;
    }

    public JButton getBtnExClie() {
        return btnExClie;
    }

    public void setBtnExClie(JButton btnExClie) {
        this.btnExClie = btnExClie;
    }

    public static JComboBox<String> getCbEstado() {
        return cbEstado;
    }

    public static void setCbEstado(JComboBox<String> cbEstado) {
        TelaCliente.cbEstado = cbEstado;
    }

    public JLabel getLblIDCliente() {
        return lblIDCliente;
    }

    public void setLblIDCliente(JLabel lblIDCliente) {
        this.lblIDCliente = lblIDCliente;
    }

    public JTable getTblClientes() {
        return tblClientes;
    }

    public void setTblClientes(JTable tblClientes) {
        this.tblClientes = tblClientes;
    }

    public static JTextField getTxtBairroCliente() {
        return txtBairroCliente;
    }

    public static void setTxtBairroCliente(JTextField txtBairroCliente) {
        TelaCliente.txtBairroCliente = txtBairroCliente;
    }

    public static JTextField getTxtCidCliente() {
        return txtCidCliente;
    }

    public static void setTxtCidCliente(JTextField txtCidCliente) {
        TelaCliente.txtCidCliente = txtCidCliente;
    }

    public static JTextField getTxtEmail() {
        return txtEmail;
    }

    public static void setTxtEmail(JTextField txtEmail) {
        TelaCliente.txtEmail = txtEmail;
    }

    public static JTextField getTxtEndCliente() {
        return txtEndCliente;
    }

    public static void setTxtEndCliente(JTextField txtEndCliente) {
        TelaCliente.txtEndCliente = txtEndCliente;
    }

    public static JFormattedTextField getTxtFoneCel() {
        return txtFoneCel;
    }

    public static void setTxtFoneCel(JFormattedTextField txtFoneCel) {
        TelaCliente.txtFoneCel = txtFoneCel;
    }

    public static JFormattedTextField getTxtFoneFixo() {
        return txtFoneFixo;
    }

    public static void setTxtFoneFixo(JFormattedTextField txtFoneFixo) {
        TelaCliente.txtFoneFixo = txtFoneFixo;
    }

    public static JTextField getTxtNomeCliente() {
        return txtNomeCliente;
    }

    public static void setTxtNomeCliente(JTextField txtNomeCliente) {
        TelaCliente.txtNomeCliente = txtNomeCliente;
    }

    public JTextField getTxtNumEndCliente() {
        return txtNumEndCliente;
    }

    public void setTxtNumEndCliente(JTextField txtNumEndCliente) {
        this.txtNumEndCliente = txtNumEndCliente;
    }

    public JTextField getTxtPesqCliente() {
        return txtPesqCliente;
    }

    public void setTxtPesqCliente(JTextField txtPesqCliente) {
        this.txtPesqCliente = txtPesqCliente;
    }

}
